apiVersion: apps/v1

# blue print for the deployment
kind: Deployment

metadata:
  name: mongodb-deployment
  labels:
    app: mongodb

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mongodb

  # blue print for the pods A => mongoDB
  template:
    metadata:
      labels:
        app: mongodb

    spec:
      containers:
        - name: mongodb
          image: mongo

          ports:
            - containerPort: 27017

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
              # value: this are saved in the secret file of k8s using its reference will use here

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
              # value: this are saved in the secret file of k8s using its reference will use here

---
apiVersion: v1
kind: Service
metadata:
 name: mongodb-service
spec:
#selector is used to connect to Pod through label.
 selector:
   app: mongodb
 ports:
   - protocol: TCP
     port: 27017
     targetPort: 27017
