apiVersion: apps/v1
# blue print for the deployment
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
  spec:
    replicas: 1 
    selector:
      matchLabels:
        app: mongodb

    # blue print for the pods
    template:
      metadata:
        labels:
          app: mongodb
      spec:
        containers:
          - name: moongodb
            image: mogodb